### ISSUE TITLE
java.lang.RuntimeException: IDs can't be null

### ISSUE THREAD

**Issue by jiangzhikele** [evanxuhe/skywalking-kubernetes#1]
您好，目前在k8s部署skywalking完成后，ui不显示任何东西。日志显示
![image](https://user-images.githubusercontent.com/38905258/60079048-c1c34d00-975f-11e9-9d51-477c1dbf10a5.png)
请问是如何修改pod时间的。安装k8s的时候已经ntp过了。这个不行吗

**Comment by weihc02** [comment]
同问，进入pod 查看事件cst时间是正常的。请问怎么处理的。

**Comment by evanxuhe** [comment]
Dockerfile中添加

# 时区修改为东八区
RUN apk add --no-cache tzdata
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

**Comment by weihc02** [comment]
进入pod 查看事件cst时间是正常的 ， 同时发现隔一段时间就没有数据进来，然后重启oap 又有数据过来，过一会，又没有数据 ，请问也跟这个有关系？？

**Comment by evanxuhe** [comment]
> 进入pod 查看事件cst时间是正常的 ， 同时发现隔一段时间就没有数据进来，然后重启oap 又有数据过来，过一会，又没有数据 ，请问也跟这个有关系？？

这个不太清楚 建议你把agent oap 的log都调到debug  再观察下ES存储数据 看看到底是在哪里断掉的

**Comment by evanxuhe** [comment]
> 进入pod 查看事件cst时间是正常的 ， 同时发现隔一段时间就没有数据进来，然后重启oap 又有数据过来，过一会，又没有数据 ，请问也跟这个有关系？？

终极办法 就是本地debug一下 看看到底是那个过程 出问题了
可以参考
[skywalking debug](https://skywalking.apache.org/zh/blog/2019-01-24-skywalking-remote-debug.html)
